### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by tarampampam** [tarampampam/mikrotik-hosts-parser#37]
- [x] Add requests logging into console
- [ ] Add metrics endpoint
- [x] "Redirect IP address" validation in UI

**Comment by tarampampam** [comment]
@Reallife do you want to implement metrics endpoint? :smile:
